#!/usr/bin/env bash

# Where we're at right now
START_WD=$(pwd -P)

# What dotfiles branch we want to install
BRANCH_NAME=$1

# All the colors we're using for notifications
SWITCH="\033["
RED="${SWITCH}0;31m"
GREEN="${SWITCH}0;32m"
YELLOW="${SWITCH}1;33m"
NORMAL="${SWITCH}0m"

# System's kernel name
KERNEL_NAME=$(uname)

set -e
echo ''

declare -A DEPENDENCIES=(
  ["curl"]="$(which curl)"
  ["git"]="$(which git)"
  ["node"]="$(which node)"
)

FILES=(
  "bash"
  "git"
  "local"
  "postgres"
  "rubygems"
  "tmux"
  "vim"
  "X"
)

# Print red
error () {
  printf "\r${RED}$1${NORMAL}\n"
  exit
}

# Print green
success () {
  printf "\r${GREEN}$1${NORMAL}\n"
}

# Print yellow
info () {
  printf "\r${YELLOW}$1${NORMAL}\n"
}

# Install suggestion
suggestion () {
  if [[ $KERNEL_NAME == "Linux" ]]; then
    CMD_NAME="sudo apt-get"
  else
    CMD_NAME="brew"
  fi

  info "$CMD_NAME install $1"
}

# Exit if installer dependecy not found
for dependency in "${!DEPENDENCIES[@]}"; do
  if [[ ! -x "${DEPENDENCIES[$dependency]}" ]]; then
    info "$dependency was not found in your system"
    suggestion $dependency

    exit 1
  fi
done

fetch_dotfiles () {
  info "Fetching dotfiles..."

  # Figure out the branch we're working on
  if ! [ $BRANCH_NAME ]; then BRANCH_NAME=master; fi

  git clone -b $BRANCH_NAME https://github.com/cloverinteractive/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
}

info "Fetching vim-plug"
curl -fLo ./vim/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

for file in "${FILES[@]}"; do
  # Rename if original exists
  [ -f "$HOME/$file" ] && mv "$HOME/$file" "$HOME/${file}.orig"

  info "Linking $file"
  stow "$file"
done

info "Installing vim plugins"
vim +PlugInstall +qa

success "Thanks for installing, please report any issues to https://github.com/cloverinteractive/dotfiles/issues"
info "Run source ~/.bash_profile to load your environment"
